-- CREATING A DATABASE NAMED AS SUBQUERIES_DATABASE
CREATE DATABASE IF NOT EXISTS Session4_V4_DATABASE;

-- USING THE DATABASE CREATED
USE Session4_V4_DATABASE;


-- Creating CUSTOMER table 
CREATE TABLE IF NOT EXISTS Blinkit_Customer_2025 -- CHILD TABLE 
(
    CUSTOMER_ID INT AUTO_INCREMENT, 
    CUSTOMER_NAME VARCHAR(100), 
    CUSTOMER_PHONE_NUMBER VARCHAR(100), 
    CUSTOMER_LOCATION_CITY VARCHAR(100), -- Foreign Key
    PRIMARY KEY (CUSTOMER_ID),
    FOREIGN KEY (CUSTOMER_LOCATION_CITY) REFERENCES Blinkit_Location_2025(LOCATION_CITY)
);

-- Creating LOCATION Table
CREATE TABLE IF NOT EXISTS Blinkit_Location_2025 -- PARENT TABLE
( 
    LOCATION_STATE VARCHAR(100), 
    LOCATION_CITY VARCHAR(100), -- Common Column acting as the reference column
    PRIMARY KEY (LOCATION_CITY)
);


-- INSERTING INTO THE LOCATION TABLE 
INSERT INTO 
BLINKIT_LOCATION_2025 (LOCATION_STATE, LOCATION_CITY)
VALUES
('Maharashtra', 'Pune'), 
('Maharashtra', 'Mumbai'), 
('Gujarat', 'Ahemdabad'), 
('Gujarat', 'Surat'), 
('Madhya Pradesh', 'Bhopal');


-- INSERTING INTO THE CUSTOMERS TABLE 
INSERT INTO 
BLINKIT_CUSTOMER_2025 (CUSTOMER_NAME, CUSTOMER_PHONE_NUMBER, CUSTOMER_LOCATION_CITY)
VALUES 
('Karan Shah', '3456789212', 'Pune'), 
('Anand Jha', '3823672212', 'Mumbai'), 
('Parth', '3456789212', 'Bhopal'), 
('Ayoush Paul', '1237873912', 'Ahemdabad');

SELECT *
FROM BLINKIT_CUSTOMER_2025;

SELECT *
FROM BLINKIT_LOCATION_2025;

-- INSERTING ANOTHER RECORD WITH A DIFFERENT CITY 
INSERT INTO 
BLINKIT_CUSTOMER_2025 (CUSTOMER_NAME, CUSTOMER_PHONE_NUMBER, CUSTOMER_LOCATION_CITY)
VALUES 
('Vinod', '8790653426', 'Baroda'); -- BEFORE INSERTING THIS RECORD IT HAS CHECKED WITH THE PARENT TABLE 






-- Creating PRODUCT_CATEGORY Table
CREATE TABLE IF NOT EXISTS Blinkit_Product_Category_2025
(
    PRODUCT_CATEGORY_ID INT AUTO_INCREMENT, 
    PRODUCT_CATEGORY_NAME VARCHAR(100), 
    PRODUCT_START_DATE DATE,
    PRIMARY KEY(PRODUCT_CATEGORY_ID), 
    UNIQUE (PRODUCT_CATEGORY_NAME)
);



-- Creating PRODUCTS Table
CREATE TABLE IF NOT EXISTS Blinkit_Products_2025
(
    PRODUCT_ID INT AUTO_INCREMENT, 
    PRODUCT_NAME VARCHAR(100), 
    PRODUCT_BRAND_NAME VARCHAR(100),
    PRODUCT_CATEGORY_NAME VARCHAR(100), -- FOREIGN KEY 
    PRIMARY KEY (PRODUCT_ID),
    FOREIGN KEY (PRODUCT_CATEGORY_NAME) REFERENCES Blinkit_Product_Category_2025(PRODUCT_CATEGORY_NAME)
);

-- inserting into the table Blinkit_Product_Category_2025
INSERT INTO Blinkit_Product_Category_2025
(PRODUCT_CATEGORY_NAME, PRODUCT_START_DATE)
VALUES
('Smart Phones', '2025-01-01'),
('Monitor', '2025-03-01'), 
('Audio Devices', '2025-05-01'), 
('Laptop', '2025-07-01');

SELECT *
FROM BLINKIT_PRODUCT_CATEGORY_2025;

INSERT INTO Blinkit_Products_2025
(PRODUCT_NAME, PRODUCT_BRAND_NAME, PRODUCT_CATEGORY_NAME)
VALUES
('Samsung S23 Ultra', 'Samsung', 'Smart Phones'),
('Apple Iphone 17 Pro Max', 'Apple', 'Smart Phones'), 
('Acer Nitro 5', 'Acer', 'Laptop');

SELECT *
FROM Blinkit_Products_2025;

INSERT INTO Blinkit_Products_2025
(PRODUCT_NAME, PRODUCT_BRAND_NAME, PRODUCT_CATEGORY_NAME)
VALUES
('Computer Table', 'IKEA', 'Furniture');


/*
Error Code: 1452. Cannot add or update a child row: a foreign key constraint fails (`session3_v4_database`.`blinkit_products_2025`, CONSTRAINT `blinkit_products_2025_ibfk_1` FOREIGN KEY (`PRODUCT_CATEGORY_NAME`) REFERENCES `blinkit_product_category_2025` (`PRODUCT_CATEGORY_NA)
*/





