-- MYSQL WORKBENCH 
CREATE DATABASE IF NOT EXISTS V31_DB;
USE V31_DB;

-- Example 1: Basic Table with Primary Key + Auto Increment
CREATE TABLE IF NOT EXISTS STUDENTS (
    STUDENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    STUDENT_NAME VARCHAR(100),
    STUDENT_CLASS VARCHAR(30)
);

-- Auto Increment works by assigning next available number
INSERT INTO STUDENTS (STUDENT_ID, STUDENT_NAME, STUDENT_CLASS) VALUES(NULL, 'Karan Shah', '10th');
SELECT * FROM STUDENTS;

-- Example 2: Primary Key without Auto Increment
CREATE TABLE IF NOT EXISTS STUDENTS_4 (
    STUDENT_ID INT PRIMARY KEY,
    STUDENT_NAME VARCHAR(100),
    STUDENT_CLASS VARCHAR(30)
);

-- This will fail if STUDENT_ID is NULL because it’s not auto-incremented
INSERT INTO STUDENTS_4 (STUDENT_ID, STUDENT_NAME, STUDENT_CLASS) VALUES(NULL, 'Karan Shah', '10th');


-- Example 3: UNIQUE with Auto Increment
CREATE TABLE IF NOT EXISTS STUDENTS_3 (
    STUDENT_ID INT UNIQUE KEY AUTO_INCREMENT,
    STUDENT_NAME VARCHAR(100),
    STUDENT_CLASS VARCHAR(30)
);

-- Multiple Insert Scenarios
INSERT INTO STUDENTS_3 (STUDENT_NAME, STUDENT_CLASS) VALUES('Akansha Jagtap', '9th');
INSERT INTO STUDENTS_3 (STUDENT_NAME, STUDENT_CLASS) VALUES('Arijit Basu', '8th');


-- Manual Insert & Auto Increment
-- Manual Entry
INSERT INTO STUDENTS (STUDENT_ID, STUDENT_NAME, STUDENT_CLASS) VALUES(20, 'Arijit Basu', '8th');

-- Duplicate ID Error
INSERT INTO STUDENTS (STUDENT_ID, STUDENT_NAME, STUDENT_CLASS) VALUES(20, 'Duplicate ID', '8th');

-- Auto Increment without ID
INSERT INTO STUDENTS (STUDENT_NAME, STUDENT_CLASS) VALUES('Nidhi Singh', '7th');

-- View All Records
SELECT * FROM STUDENTS;


-- Delete Record & Alter Auto Increment Value
-- Delete a record
DELETE FROM STUDENTS WHERE STUDENT_ID = 4;

-- Alter the AUTO_INCREMENT start point
ALTER TABLE STUDENTS AUTO_INCREMENT = 100;

-- New Inserts after altering
INSERT INTO STUDENTS (STUDENT_NAME, STUDENT_CLASS) VALUES('Arijit Basu', '8th');


-- Snowflake Implementation
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

CREATE DATABASE IF NOT EXISTS V3_DB_AUTO_INCREMENT;
CREATE SCHEMA IF NOT EXISTS V3_DB_AUTO_INCREMENT_SCHEMA;

USE DATABASE V3_DB_AUTO_INCREMENT;
USE SCHEMA V3_DB_AUTO_INCREMENT_SCHEMA;


-- Example 1: Basic Table with AUTOINCREMENT
CREATE TABLE IF NOT EXISTS STUDENTS (
    STUDENT_ID INT PRIMARY KEY AUTOINCREMENT,
    STUDENT_NAME VARCHAR(100),
    STUDENT_CLASS VARCHAR(30)
);

INSERT INTO STUDENTS (STUDENT_NAME, STUDENT_CLASS) VALUES('Karan Shah', '10TH');
INSERT INTO STUDENTS (STUDENT_NAME, STUDENT_CLASS) VALUES('Nidhi Singh', '9TH');

SELECT * FROM STUDENTS;


-- Example 2: AUTOINCREMENT with START/INCREMENT
CREATE TABLE IF NOT EXISTS STUDENTS_1 (
    STUDENT_ID INT PRIMARY KEY AUTOINCREMENT START 1 INCREMENT 1,
    STUDENT_NAME VARCHAR(100),
    STUDENT_CLASS VARCHAR(30)
);

INSERT INTO STUDENTS_1 (STUDENT_NAME, STUDENT_CLASS) VALUES('Karan Shah', '10TH');


-- Using Sequences (Recommended in Snowflake)
-- Method 1: Manually Assign NEXTVAL
CREATE OR REPLACE SEQUENCE STUDENT_ID_AUTO_INCREMENTER START = 1 INCREMENT = 1;

CREATE TABLE IF NOT EXISTS STUDENTS_2 (
    STUDENT_ID INT PRIMARY KEY,
    STUDENT_NAME VARCHAR(100),
    STUDENT_CLASS VARCHAR(30)
);

INSERT INTO STUDENTS_2 (STUDENT_ID, STUDENT_NAME, STUDENT_CLASS)
VALUES (STUDENT_ID_AUTO_INCREMENTER.NEXTVAL, 'Karan Shah', '10th');

SELECT * FROM STUDENTS_2;


-- Method 2: Use DEFAULT with Sequence
CREATE OR REPLACE SEQUENCE STUDENT_ID_AUTO_INCREMENTER_1 START = 1 INCREMENT = 1;

CREATE TABLE IF NOT EXISTS STUDENTS_3 (
    STUDENT_ID INT DEFAULT STUDENT_ID_AUTO_INCREMENTER_1.NEXTVAL,
    STUDENT_NAME VARCHAR(100),
    STUDENT_CLASS VARCHAR(30)
);

-- Insert without specifying ID
INSERT INTO STUDENTS_3 (STUDENT_NAME, STUDENT_CLASS) VALUES('Sagar Pol', '10th');
SELECT * FROM STUDENTS_3;


-- Set Custom Starting Value in Sequence
CREATE OR REPLACE SEQUENCE STUDENT_ID_AUTO_INCREMENTER_3 START = 110000 INCREMENT = 1;

CREATE TABLE IF NOT EXISTS STUDENTS_5 (
    STUDENT_ID INT DEFAULT STUDENT_ID_AUTO_INCREMENTER_3.NEXTVAL,
    STUDENT_NAME VARCHAR(100),
    STUDENT_CLASS VARCHAR(30)
);

INSERT INTO STUDENTS_5 (STUDENT_NAME, STUDENT_CLASS) VALUES('Tarzen Sharma', '10th');
SELECT * FROM STUDENTS_5;



-- Snowflake AUTOINCREMENT with ORDER Clause (Optional)
CREATE TABLE IF NOT EXISTS STUDENTS_7 (
    STUDENT_ID INT AUTOINCREMENT START 1 INCREMENT 1 ORDER,
    STUDENT_NAME VARCHAR(100),
    STUDENT_CLASS VARCHAR(30)
);

-- Inserts and manual ID override
INSERT INTO STUDENTS_7 (STUDENT_NAME, STUDENT_CLASS) VALUES('Sunil Verma', '10th');
INSERT INTO STUDENTS_7 (STUDENT_ID, STUDENT_NAME, STUDENT_CLASS) VALUES(6, 'Anand Jha', '10th');
SELECT * FROM STUDENTS_7;



-- Primary Key Violation Example
CREATE TABLE IF NOT EXISTS STUDENTS_8 (
    STUDENT_ID INT PRIMARY KEY AUTOINCREMENT START 1 INCREMENT 1 ORDER,
    STUDENT_NAME VARCHAR(100),
    STUDENT_CLASS VARCHAR(30)
);

-- Duplicate primary key value (will cause error)
INSERT INTO STUDENTS_8 (STUDENT_ID, STUDENT_NAME, STUDENT_CLASS) VALUES(1, 'Tarzen Sharma', '10th');
INSERT INTO STUDENTS_8 (STUDENT_ID, STUDENT_NAME, STUDENT_CLASS) VALUES(1, 'Anand Jha', '10th');

SELECT * FROM STUDENTS_8;


/*
	Summary for Students
	MySQL: AUTO_INCREMENT works directly with PRIMARY KEY.

	Snowflake:
	Use AUTOINCREMENT in column definition.
	OR define a SEQUENCE object and use NEXTVAL.
	DEFAULT sequence.NEXTVAL allows automatic value insertion.
	Avoid manual ID overrides unless necessary.
	PRIMARY KEY enforces uniqueness; inserting duplicate keys causes an error.
*/





